[phases.setup]
nixPkgs = ["...", "prisma-engines", "postgresql"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate"]

[phases.start]
cmds = [
  "npx prisma db execute --file ./prisma/migration.sql --schema ./prisma/schema.prisma",
  "npx prisma db push --skip-generate --accept-data-loss",
  "node prisma/seed.js || echo 'Seed failed, continuing with server start'",
  "node src/server.js"
]
