[phases.setup]
nixPkgs = ["...", "prisma-engines", "poppler"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate"]

[phases.start]
cmds = [
  "npx prisma db push --accept-data-loss 2>&1",
  "node src/server.js"
]
